import {
  gabigol,
  arrascaeta,
  pedro,
  brunohenrique,
  evertonribeiro,
  vidal,
  thiagomaia,
  filipeluis,
  rodrigocaio,
  davidluiz,
  santos,
  neneca,
  matheuscunha,
  matheuzinho,
  mgoncalves,
  ayrtonlucas,
  vitorhugo,
  varela,
  pablo,
  cebolinha,
  cleiton,
  fabriciobruno,
  leopereira,
  marinho,
  matheusfranca,
  pulgar,
  alexSandro,
  alextelles,
  alisson,
  antony,
  arana,
  brunoguimaraes,
  casemiro,
  coutinho,
  cunha,
  danielalves,
  danilosantos,
  ederson,
  fabinho,
  fred,
  gabrieljesus,
  gerson,
  magalhaes,
  marquinhos,
  martinelli,
  militao,
  neymar,
  paqueta,
  raphinha,
  richarlison,
  rodrygo,
  thiagosilva,
  vini,
  weverton,
} from "./playersPictures.js";

interface Player {
  [key: string]: {
    name: string;
    num: number;
    img: string;
    pos: "G" | "D" | "L" | "V" | "M" | "A" | "P";
  }[];
}
const players: Player = {
  flamengo: [
    {
      name: "Gabigol",
      num: 10,
      img: gabigol,
      pos: "A",
    },
    {
      name: "Arrascaeta",
      num: 14,
      img: arrascaeta,
      pos: "M",
    },
    {
      name: "Pedro",
      num: 9,
      img: pedro,
      pos: "A",
    },
    {
      name: "Éverton Ribeiro",
      num: 7,
      img: evertonribeiro,
      pos: "M",
    },
    {
      name: "Vidal",
      num: 32,
      img: vidal,
      pos: "V",
    },
    {
      name: "Filipe Luis",
      num: 16,
      img: filipeluis,
      pos: "L",
    },
    {
      name: "David Luiz",
      num: 23,
      img: davidluiz,
      pos: "D",
    },
    {
      name: "Rodrigo Caio",
      num: 3,
      img: rodrigocaio,
      pos: "D",
    },
    {
      name: "Santos",
      num: 20,
      img: santos,
      pos: "G",
    },
    {
      name: "Erick Pulgar",
      num: 5,
      img: pulgar,
      pos: "V",
    },
    {
      name: "Cebolinha",
      num: 19,
      img: cebolinha,
      pos: "P",
    },
    {
      name: "Thiago Maia",
      num: 8,
      img: thiagomaia,
      pos: "V",
    },
    {
      name: "Bruno Henrique",
      num: 27,
      img: brunohenrique,
      pos: "A",
    },
    {
      name: "Léo Pereira",
      num: 4,
      img: leopereira,
      pos: "D",
    },
    {
      name: "Matheuzinho",
      num: 34,
      img: matheuzinho,
      pos: "L",
    },
    {
      name: "Fabricio Bruno",
      num: 15,
      img: fabriciobruno,
      pos: "D",
    },
    {
      name: "Pablo",
      num: 30,
      img: pablo,
      pos: "D",
    },
    {
      name: "Ayrton Lucas",
      num: 6,
      img: ayrtonlucas,
      pos: "L",
    },
    {
      name: "Hugo Neneca",
      num: 45,
      img: neneca,
      pos: "G",
    },
    {
      name: "Marinho",
      num: 31,
      img: marinho,
      pos: "P",
    },
    { name: "Matheus Gonçalves", num: 40, img: mgoncalves, pos: "M" },
    {
      name: "Matheus França",
      num: 42,
      img: matheusfranca,
      pos: "M",
    },
    {
      name: "Guilhermo Varela",
      num: 2,
      img: varela,
      pos: "L",
    },
    {
      name: "Vitor Hugo",
      num: 29,
      img: vitorhugo,
      pos: "M",
    },
    {
      name: "Matheus Cunha",
      num: 51,
      img: matheuscunha,
      pos: "G",
    },
    {
      name: "Cleiton",
      num: 33,
      img: cleiton,
      pos: "D",
    },
    {
      name: "Gerson",
      num: 20,
      img: gerson,
      pos: "V",
    },
  ],
  selecao: [
    {
      name: "Neymar",
      num: 10,
      img: neymar,
      pos: "A",
    },
    {
      name: "Vinicius Junior",
      num: 18,
      img: vini,
      pos: "P",
    },
    {
      name: "Antony",
      num: 77,
      img: antony,
      pos: "P",
    },
    {
      name: "Richarlison",
      num: 7,
      img: richarlison,
      pos: "A",
    },
    {
      name: "Paquetá",
      num: 17,
      img: paqueta,
      pos: "M",
    },
    {
      name: "Casemiro",
      num: 5,
      img: casemiro,
      pos: "V",
    },
    {
      name: "Fred",
      num: 8,
      img: fred,
      pos: "V",
    },
    {
      name: "Raphinha",
      num: 22,
      img: raphinha,
      pos: "P",
    },
    {
      name: "Gerson",
      num: 96,
      img: gerson,
      pos: "M",
    },
    {
      name: "Alex Sandro",
      num: 6,
      img: alexSandro,
      pos: "L",
    },
    {
      name: "Alex Telles",
      num: 36,
      img: alextelles,
      pos: "L",
    },
    {
      name: "Alisson",
      num: 1,
      img: alisson,
      pos: "G",
    },
    {
      name: "Arana",
      num: 46,
      img: arana,
      pos: "L",
    },
    {
      name: "B. Guimarães",
      num: 28,
      img: brunoguimaraes,
      pos: "M",
    },
    {
      name: "Coutinho",
      num: 11,
      img: coutinho,
      pos: "M",
    },
    {
      name: "Matheus Cunha",
      num: 79,
      img: cunha,
      pos: "A",
    },
    {
      name: "Daniel Alves",
      num: 66,
      img: danielalves,
      pos: "L",
    },
    {
      name: "Danilo Santos",
      num: 68,
      img: danilosantos,
      pos: "V",
    },
    {
      name: "Ederson",
      num: 23,
      img: ederson,
      pos: "G",
    },
    {
      name: "Fabinho",
      num: 15,
      img: fabinho,
      pos: "V",
    },
    {
      name: "G. Magalhaes",
      num: 52,
      img: magalhaes,
      pos: "D",
    },
    {
      name: "Marquinhos",
      num: 4,
      img: marquinhos,
      pos: "D",
    },
    {
      name: "Martinelli",
      num: 91,
      img: martinelli,
      pos: "A",
    },
    {
      name: "Militao",
      num: 14,
      img: militao,
      pos: "D",
    },
    {
      name: "Rodrygo",
      num: 89,
      img: rodrygo,
      pos: "P",
    },
    {
      name: "Pedro",
      num: 93,
      img: pedro,
      pos: "A",
    },
    {
      name: "Weverton",
      num: 12,
      img: weverton,
      pos: "G",
    },
    {
      name: "G. Jesus",
      num: 9,
      img: gabrieljesus,
      pos: "A",
    },
    {
      name: "Thiago Silva",
      num: 3,
      img: thiagosilva,
      pos: "D",
    },
    {
      name: "Gabigol",
      num: 69,
      img: gabigol,
      pos: "A",
    },
  ],
};
// const sortedPlayers = players.sort((a, b) => a.num - b.num);

export { players };
