const fourFourTwo = {
    first: { top: "1%", left: "42.5%" },
    second: { top: "22%", left: "7%" },
    third: { top: "22%", left: "78%" },
    fourth: { top: "10%", left: "25%" },
    fifth: { top: "10%", left: "60%" },
    sixth: { top: " 40%", left: "20%" },
    seventh: { top: "40%", left: "65%" },
    eighth: { top: "60%", left: "10%" },
    ninth: { top: "60%", left: "75%" },
    tenth: { top: "80%", left: "25%" },
    eleventh: { top: "80%", left: "60%" },
  };
const fourFourTwoLosangle = {
    first: { top: "1%", left: "42.5%" },
    second: { top: "22%", left: "7%" },
    third: { top: "22%", left: "78%" },
    fourth: { top: "10%", left: "25%" },
    fifth: { top: "10%", left: "60%" },
    sixth: { top: " 36%", left: "42.5%" },
    seventh: { top: "49%", left: "70%" },
    eighth: { top: "49%", left: "15%" },
    ninth: { top: "60%", left: "42.5%" },
    tenth: { top: "80%", left: "25%" },
    eleventh: { top: "80%", left: "60%" },
}
const fourThreeThree = {
    first: { top: "1%", left: "42.5%" },
    second: { top: "22%", left: "7%" },
    third: { top: "22%", left: "78%" },
    fourth: { top: "10%", left: "25%" },
    fifth: { top: "10%", left: "60%" },
    sixth: { top: " 40%", left: "42%" },
    seventh: { top: "55%", left: "69%" },
    eighth: { top: "55%", left: "15%" },
    ninth: { top: "80%", left: "75%" },
    tenth: { top: "80%", left: "10%" },
    eleventh: { top: "80%", left: "42%" },
}
const threeFiveTwo = {
    first: { top: "1%", left: "42.5%" },
    second: { top: "15%", left: "10%" },
    third: { top: "35%", left: "5%" },
    fourth: { top: "15%", left: "42.5%" },
    fifth: { top: "15%", left: "75%" },
    sixth: { top: " 35%", left: "78%" },
    seventh: { top: "40%", left: "42.5%" },
    eighth: { top: "60%", left: "15%" },
    ninth: { top: "60%", left: "70%" },
    tenth: { top: "80%", left: "25%" },
    eleventh: { top: "80%", left: "60%" },
}  
export { fourFourTwo,fourFourTwoLosangle, fourThreeThree, threeFiveTwo}  